### ISSUE TITLE
Add @ngx-env/builder to the list of builders

### ISSUE THREAD

**Issue by chihab** [ngx-builders/angular-builder#172]
First of all, thanks for this project. It was an inspiration and a good resource for me to build the `@ngx-env/builder`.

I suggest to add `@ngx-env/builder` 👇 to the list of builders.

## Usage

1. **Add @ngx-env to your CLI project**

```sh
ng add @ngx-env/builder
```

2. **Define Environment Variables in `.env`**

```sh
NG_APP_ENABLE_ANALYTICS=false
NG_APP_VERSION=$npm_package_version
NG_APP_COMMIT=$GITHUB_SHA
```

3. **Use in TS and HTML**

```ts
@Component({
  selector: "app-footer",
})
export class FooterComponent {
  version = process.env.NG_APP_VERSION;
  branch = process.env.NG_APP_BRANCH_NAME;
  commit = process.env.NG_APP_COMMIT;
  analyticsFlag = process.env.NG_APP_ENABLE_ANALYTICS;
}
```

```html
<!-- Same output in the spans -->
<span> {{ 'process.env.NG_APP_BRANCH_NAME' | env }} </span>
<span> {{ 'NG_APP_BRANCH_NAME' | env }} </span>
<span> {{ branch }} </span>
```

```html
<!-- index.html -->
<head>
  <title>NgApp on %NG_APP_BRANCH_NAME%</title>
</head>
```

4. **Run your CLI commands**

```sh
npm start
NG_APP_BRANCH_NAME=$GITHUB_HEAD_REF ng test
NG_APP_BRANCH_NAME=`git branch --show-current` npm run build
```

## Documentation
- [README](https://github.com/chihab/ngx-env#readme)
- [InDepth Article](https://indepth.dev/tutorials/angular/inject-environment-variables)

## Links
- [npm package](https://www.npmjs.com/package/@ngx-env/builder)
- [GitHub repository](http://github.com/chihab/ngx-env)

And please let me know if you think about any good feature to add to the project. 💙

**Comment by santoshyadavdev** [comment]
Thank you @chihab, can you raise a PR for the same.
