### ISSUE TITLE
Add search functionality and Mat Expander

### ISSUE THREAD

**Issue by santoshyadav198613** [ngx-builders/angular-builder#2]
Currently, UI is not clean need to make it better.
1. Replace bootstrap accordion with mat expander.
2. Add Search functionality.

**Comment by Splaktar** [comment]
I don't think that the accordions add much useful functionality.

It would be nice to have a filter feature to filter by words in both the name and description of the builders.

**Comment by santoshyadav198613** [comment]
Thanks Michael, yes planning to add it.
